# Site settings
name: Debojit Nath
title: Debojit Nath | Data Scientist
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://debojit10.github.io/
baseurl: ''
email: brittany.chiang@gmail.com
cover: https://debojit10.github.io/img/og.png
logo: https://debojit10.github.io/img/emojis/technologist.png
resume: https://debojit10.github.io/resume.pdf
social:
  - title: email
    url: mailto:nathdebojit2000@gmail.com
  - title: github
    url: https://github.com/debojit10
  - title: linkedin
    url: https://www.linkedin.com/in/debojit-nath/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
